import { pokemonData } from '../data/pokemon'
import type { Case, Evidence, InspectedFact, Location, Suspect } from './caseModel'
import { getAbilityText, getEvolutionLineText, getHabitatNote } from './suspectCaseFile'

const getPokemon = (pokemonId: number) => {
  const pokemon = pokemonData.find((entry) => entry.id === pokemonId)

  if (!pokemon) {
    throw new Error(`Pokemon ${pokemonId} not found in local data.`)
  }

  return pokemon
}

const createHiddenFacts = (pokemonId: number): InspectedFact[] => {
  const pokemon = getPokemon(pokemonId)

  return [
    {
      key: 'type',
      label: 'Type',
      value: pokemon.types.map((type) => type[0].toUpperCase() + type.slice(1)).join(' / '),
      discovered: false,
    },
    {
      key: 'region',
      label: 'Region',
      value: pokemon.region,
      discovered: false,
    },
    {
      key: 'height',
      label: 'Height',
      value: `${pokemon.heightM} m`,
      discovered: false,
    },
    {
      key: 'weight',
      label: 'Weight',
      value: `${pokemon.weightKg} kg`,
      discovered: false,
    },
    {
      key: 'ability',
      label: 'Ability',
      value: getAbilityText(pokemonId),
      discovered: false,
    },
    {
      key: 'evolution-line',
      label: 'Evolution line',
      value: getEvolutionLineText(pokemon),
      discovered: false,
    },
    {
      key: 'habitat-note',
      label: 'Habitat note',
      value: getHabitatNote(pokemonId),
      discovered: false,
    },
  ]
}

const createSuspect = (pokemonId: number): Suspect => {
  const pokemon = getPokemon(pokemonId)

  return {
    pokemonId,
    name: pokemon.name,
    sprite: pokemon.sprite,
    manuallyRuledOut: false,
    noteStatus: 'suspect',
    inspectedGroups: {
      appearance: false,
      records: false,
      habitat: false,
      ability: false,
    },
    inspectedFacts: createHiddenFacts(pokemonId),
  }
}

const evidence: Evidence[] = [
  {
    id: 'cookie-crumbs',
    title: 'Cookie Crumbs',
    clueText: 'Fresh crumbs were scattered low across the ground.',
    hiddenTrait: 'small_low',
    endExplanation: 'The culprit moved close to the ground while eating near the campfire.',
    discovered: false,
  },
  {
    id: 'quiet-digging',
    title: 'Quiet Digging',
    clueText: 'Someone heard soft scraping after midnight.',
    hiddenTrait: 'digging',
    endExplanation: 'The culprit spent time scratching or digging near camp overnight.',
    discovered: false,
  },
  {
    id: 'small-footprints',
    title: 'Small Footprints',
    clueText: 'The tracks were small and close to the ground.',
    hiddenTrait: 'small_low',
    endExplanation: 'The culprit left small, low tracks near the tents.',
    discovered: false,
  },
  {
    id: 'sand-trail',
    title: 'Sand Trail',
    clueText: 'A faint trail of dry grit pulled away from the camp.',
    hiddenTrait: 'ground_or_sand',
    endExplanation: 'The culprit carried dry grit away from the tracks.',
    discovered: false,
  },
  {
    id: 'loose-soil',
    title: 'Loose Soil',
    clueText: 'Fresh soil had been disturbed under the tree roots.',
    hiddenTrait: 'digging',
    endExplanation: 'Something recently dug into the loose soil at the forest edge.',
    discovered: false,
  },
  {
    id: 'scratch-marks',
    title: 'Scratch Marks',
    clueText: 'Narrow marks scored the cookie jar lid.',
    hiddenTrait: 'claws_or_scratching',
    endExplanation: 'The culprit left narrow scratch marks while opening the jar.',
    discovered: false,
  },
  {
    id: 'low-crumbs',
    title: 'Low Crumbs',
    clueText: 'Crumbs had fallen low along the edge of the table.',
    hiddenTrait: 'small_low',
    endExplanation: 'The culprit moved low beside the table while carrying crumbs away.',
    discovered: false,
  },
  {
    id: 'avoided-water',
    title: 'Avoided Water',
    clueText: 'The camper remembered the culprit skirting around the water bucket.',
    hiddenTrait: 'dry_ground_dislike_water',
    endExplanation: 'The culprit deliberately avoided the wettest part of camp.',
    discovered: false,
  },
  {
    id: 'dry-trail',
    title: 'Dry Trail',
    clueText: 'A dry path of grit led away from the wash bucket.',
    hiddenTrait: 'ground_or_sand',
    endExplanation: 'The culprit carried dry grit even near the water station.',
    discovered: false,
  },
]

const locations: Location[] = [
  {
    id: 'campsite',
    name: 'Campsite',
    icon: '🏕️',
    teaserText: 'The campsite looks recently disturbed.',
    investigated: false,
    selectedActionId: null,
    actions: [
      {
        id: 'crumbs',
        label: 'Examine the crumbs',
        leadType: 'careful',
        description: 'Inspect traces near the fire pit.',
        outcomeType: 'evidence',
        evidenceId: 'cookie-crumbs',
        evidenceTitle: 'Cookie Crumbs',
        evidenceText: 'Fresh crumbs were scattered low across the ground.',
        observationText: 'Something small disturbed the snack area.',
        implicationText: 'The culprit may have stayed close to the ground.',
        unlocksLocationIds: [],
        isUseful: true,
      },
      {
        id: 'tents',
        label: 'Search the tents',
        leadType: 'thorough',
        description: 'Check sleeping bags and gear.',
        outcomeType: 'nothing',
        evidenceId: null,
        evidenceTitle: null,
        evidenceText: null,
        observationText: 'The tents are messy, but nothing points to the culprit.',
        unlocksLocationIds: [],
        isUseful: false,
      },
      {
        id: 'campers',
        label: 'Interview nearby campers',
        leadType: 'uncertain',
        description: 'Ask what they heard overnight.',
        outcomeType: 'witness',
        evidenceId: 'quiet-digging',
        evidenceTitle: 'Quiet Digging',
        evidenceText: 'Someone heard soft scraping after midnight.',
        observationText: 'The witness sounded sleepy, but consistent.',
        implicationText: 'The culprit may have been scratching or digging in the dark.',
        unlocksLocationIds: [],
        isUseful: true,
      },
    ],
  },
  {
    id: 'footprints',
    name: 'Footprints',
    icon: '👣',
    teaserText: 'Something passed behind the tents.',
    investigated: false,
    selectedActionId: null,
    actions: [
      {
        id: 'measure-tracks',
        label: 'Measure the tracks',
        leadType: 'careful',
        description: 'Check the size of the prints.',
        outcomeType: 'evidence',
        evidenceId: 'small-footprints',
        evidenceTitle: 'Small Footprints',
        evidenceText: 'The tracks were small and close to the ground.',
        observationText: 'The prints stay tight and shallow beside the tents.',
        implicationText: 'The culprit may have moved low and lightly.',
        unlocksLocationIds: [],
        isUseful: true,
      },
      {
        id: 'follow-tracks',
        label: 'Follow the tracks',
        leadType: 'risky',
        description: 'Follow where the trail breaks away.',
        outcomeType: 'evidence',
        evidenceId: 'sand-trail',
        evidenceTitle: 'Sand Trail',
        evidenceText: 'A faint trail of dry grit pulled away from the camp.',
        observationText: 'The tracks break apart into a dry trail behind the tents.',
        implicationText: 'The culprit may have carried dry grit away from camp.',
        unlocksLocationIds: [],
        isUseful: true,
      },
      {
        id: 'photograph-tracks',
        label: 'Photograph the tracks',
        leadType: 'quick',
        description: 'Capture the tracks before they blur.',
        outcomeType: 'nothing',
        evidenceId: null,
        evidenceTitle: null,
        evidenceText: null,
        observationText: 'The picture is clear, but it gives you nothing new.',
        unlocksLocationIds: [],
        isUseful: false,
      },
    ],
  },
  {
    id: 'forest-edge',
    name: 'Forest Edge',
    icon: '🌲',
    teaserText: 'The soil near the roots looks unusual.',
    investigated: false,
    selectedActionId: null,
    actions: [
      {
        id: 'check-roots',
        label: 'Check the tree roots',
        leadType: 'careful',
        description: 'Inspect the soil under the roots.',
        outcomeType: 'evidence',
        evidenceId: 'loose-soil',
        evidenceTitle: 'Loose Soil',
        evidenceText: 'Fresh soil had been disturbed under the tree roots.',
        observationText: 'Something recently scratched through the roots and left the soil loose.',
        implicationText: 'The culprit may have spent time digging through dry soil.',
        unlocksLocationIds: [],
        isUseful: true,
      },
      {
        id: 'search-branches',
        label: 'Search the branches',
        leadType: 'thorough',
        description: 'Check the branches above eye level.',
        outcomeType: 'nothing',
        evidenceId: null,
        evidenceTitle: null,
        evidenceText: null,
        observationText: 'Broken twigs and leaves make noise, but reveal nothing useful.',
        unlocksLocationIds: [],
        isUseful: false,
      },
      {
        id: 'listen-quietly',
        label: 'Listen quietly',
        leadType: 'uncertain',
        description: 'Pause and listen for movement.',
        outcomeType: 'nothing',
        evidenceId: null,
        evidenceTitle: null,
        evidenceText: null,
        observationText: 'The woods stay still. If someone was here, they are long gone.',
        unlocksLocationIds: [],
        isUseful: false,
      },
    ],
  },
  {
    id: 'cookie-jar',
    name: 'Cookie Jar',
    icon: '🍪',
    teaserText: 'The empty jar sits slightly crooked.',
    investigated: false,
    selectedActionId: null,
    actions: [
      {
        id: 'inspect-lid',
        label: 'Inspect the lid',
        leadType: 'obvious',
        description: 'Study where the lid was forced open.',
        outcomeType: 'evidence',
        evidenceId: 'scratch-marks',
        evidenceTitle: 'Scratch Marks',
        evidenceText: 'Narrow marks scored the cookie jar lid.',
        observationText: 'Something scraped hard against the lid before it gave way.',
        implicationText: 'The culprit may have forced the lid open with a scraping motion.',
        unlocksLocationIds: [],
        isUseful: true,
      },
      {
        id: 'smell-jar',
        label: 'Smell the jar',
        leadType: 'risky',
        description: 'Check for any lingering scent.',
        outcomeType: 'nothing',
        evidenceId: null,
        evidenceTitle: null,
        evidenceText: null,
        observationText: 'It only smells sweet and stale. Nothing useful lingers.',
        unlocksLocationIds: [],
        isUseful: false,
      },
      {
        id: 'check-table',
        label: 'Check the table',
        leadType: 'careful',
        description: 'Look along the table edge.',
        outcomeType: 'evidence',
        evidenceId: 'low-crumbs',
        evidenceTitle: 'Low Crumbs',
        evidenceText: 'Crumbs had fallen low along the edge of the table.',
        observationText: 'Whoever reached the jar left crumbs closer to the lower edge than the top.',
        implicationText: 'The culprit may have been lower to the ground than expected.',
        unlocksLocationIds: [],
        isUseful: true,
      },
    ],
  },
  {
    id: 'witness-tent',
    name: 'Witness Tent',
    icon: '🛏️',
    teaserText: 'A sleepy camper remembers something.',
    investigated: false,
    selectedActionId: null,
    actions: [
      {
        id: 'interview-camper',
        label: 'Interview the sleepy camper',
        leadType: 'uncertain',
        description: 'Ask what the camper remembers.',
        outcomeType: 'witness',
        evidenceId: 'avoided-water',
        evidenceTitle: 'Avoided Water',
        evidenceText: 'The camper remembered the culprit skirting around the water bucket.',
        observationText: 'The witness is tired, but certain about that detail.',
        implicationText: 'The culprit may have preferred to keep to the driest path.',
        unlocksLocationIds: [],
        isUseful: true,
      },
      {
        id: 'check-wash-bucket',
        label: 'Check the wash bucket',
        leadType: 'careful',
        description: 'Inspect the ground by the bucket.',
        outcomeType: 'evidence',
        evidenceId: 'dry-trail',
        evidenceTitle: 'Dry Trail',
        evidenceText: 'A dry path of grit led away from the wash bucket.',
        observationText: 'Even near the water, the path stayed oddly dry.',
        implicationText: 'The culprit may have avoided the wet ground entirely.',
        unlocksLocationIds: [],
        isUseful: true,
      },
      {
        id: 'search-bedding',
        label: 'Search the bedding',
        leadType: 'thorough',
        description: 'Check the blankets and bedding.',
        outcomeType: 'nothing',
        evidenceId: null,
        evidenceTitle: null,
        evidenceText: null,
        observationText: 'The bedding is warm and crumpled, but it hides nothing useful.',
        unlocksLocationIds: [],
        isUseful: false,
      },
    ],
  },
]

const missingCookiesCase: Case = {
  id: 'missing-cookies',
  title: 'The Missing Cookies',
  shortStory: 'Someone snuck into camp overnight and ate all the cookies.',
  crimeIcon: '🍪',
  difficulty: 'easy',
  culpritPokemonId: 27,
  maxInvestigations: 5,
  suspects: [54, 27, 58, 252, 322, 328].map(createSuspect),
  locations,
  evidence,
  solution: {
    culpritRevealText: 'Sandshrew was behind the case.',
    detectiveConclusion:
      'The culprit had to be small, close to the ground, comfortable around dry soil, and likely capable of scratching or digging. Sandshrew best fit the collected evidence.',
    evidenceExplanation: [
      {
        locationId: 'campsite',
        evidenceTitle: 'Cookie Crumbs',
        clueText: 'Fresh crumbs were scattered low across the ground.',
        deductionText: 'This pointed toward a small Pokemon that stayed low while moving through camp.',
      },
      {
        locationId: 'footprints',
        evidenceTitle: 'Small Footprints',
        clueText: 'The tracks were small and close to the ground.',
        deductionText: 'The culprit was light, low, and careful around the tents.',
      },
      {
        locationId: 'forest-edge',
        evidenceTitle: 'Loose Soil',
        clueText: 'Fresh soil had been disturbed under the tree roots.',
        deductionText: 'Digging behavior made Sandshrew far more likely than the other suspects.',
      },
      {
        locationId: 'cookie-jar',
        evidenceTitle: 'Scratch Marks',
        clueText: 'Narrow marks scored the cookie jar lid.',
        deductionText: 'The culprit likely used claws or scraping motions to force the lid open.',
      },
      {
        locationId: 'witness-tent',
        evidenceTitle: 'Avoided Water',
        clueText: 'The camper remembered the culprit skirting around the water bucket.',
        deductionText: 'That behavior fit a Pokemon more comfortable in dry ground than near water.',
      },
    ],
    clearedSuspects: [
      {
        pokemonId: 54,
        reason: 'Too connected to water for the dry trail and avoided-water clues.',
      },
      {
        pokemonId: 58,
        reason: 'Did not explain the small, low tracks left near the tents.',
      },
      {
        pokemonId: 252,
        reason: 'Did not fit the dry soil and digging evidence as strongly.',
      },
      {
        pokemonId: 322,
        reason: 'Too bulky for the small footprints and low crumb trail.',
      },
      {
        pokemonId: 328,
        reason: 'Shared some clues, but did not explain the jar scratches as well.',
      },
    ],
  },
  status: 'active',
}

export const createMissingCookiesCase = (): Case => ({
  ...missingCookiesCase,
  suspects: missingCookiesCase.suspects.map((suspect) => ({
    ...suspect,
    inspectedGroups: { ...suspect.inspectedGroups },
    inspectedFacts: suspect.inspectedFacts.map((fact) => ({ ...fact })),
  })),
  locations: missingCookiesCase.locations.map((location) => ({
    ...location,
    actions: location.actions.map((action) => ({ ...action })),
  })),
  evidence: missingCookiesCase.evidence.map((evidenceItem) => ({ ...evidenceItem })),
  solution: missingCookiesCase.solution
    ? {
        ...missingCookiesCase.solution,
        evidenceExplanation: missingCookiesCase.solution.evidenceExplanation.map((item) => ({ ...item })),
        clearedSuspects: missingCookiesCase.solution.clearedSuspects.map((item) => ({ ...item })),
      }
    : undefined,
})
